import type { Metadata } from "next";
import "../styles/globals.css"
import { inter } from "@/lib/font";
import Background from "@/layout/Background";
import { ToastProvider } from "@/shared/context/ToastContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full relative overflow-x-hidden">
        <ToastProvider>
          <Background/>
          {children}
        </ToastProvider>
      </body>
    </html>
  );
}
